export const places = {
  paper: {name:'Paper Workshop', number:'01', subtitle:'A desk for every chapter.', intro:'Start with the things I build. Choose a desk, or walk over and explore.', theme:'warm'},
  night: {name:'After Hours Studio', number:'02', subtitle:'A closer look at the work.', intro:'Take a seat, switch on a lamp, and look inside the projects.', theme:'night'},
  islands: {name:'Career Archipelago', number:'03', subtitle:'Follow the path from build to lead.', intro:'Cross the bridges between applications, document AI, and engineering leadership.', theme:'sea'}
};
export const stories = {
  build:{eyebrow:'01 / Build',title:'Mobile & web',subtitle:'Sribuu · BintanGO · Telkomcel',body:'I started with web and mobile applications, then grew into leading mobile teams. The work expanded from writing features to shaping architecture, reviewing code, and helping other engineers.',facts:[['Sribuu','Built the Flutter apps and later led the mobile team. Clean architecture, code reviews, research, and optimisation.'],['BintanGO','Led and trained the mobile team, with responsibility for code reviews and app architecture.'],['Telkomcel','Developed commercial apps including Mytimor, Musica, and the eLib-UNTL digital library.']],link:'/#experience',linkText:'Full experience'},
  ai:{eyebrow:'02 / Explore',title:'Documents into data',subtitle:'Fintelite · Machine Learning Engineer · 2024',body:'I built OCR models and pipelines for text detection, recognition, and entity extraction, integrating LLMs into document processing. Later, as Tech Lead, I fine-tuned LLMs with the Data Team to improve extraction accuracy.',facts:[['A small example','Run the document machine to see a synthetic invoice mapped to named fields. This is a scripted illustration, not a live OCR service.']],link:'/#document-demo',linkText:'See the document example',demo:true},
  lead:{eyebrow:'03 / Lead',title:'Engineering at Fintelite',subtitle:'Tech Lead · July 2024–present',body:'I manage engineers across Fintelite Group’s AI-powered fintech products, including AnyCheck. The work connects architecture and technical delivery with product priorities.',facts:[['Systems','Reduced infrastructure costs while improving system performance. The measured result is in the main portfolio.'],['Delivery','Eliminated critical technical debt and modernised architecture to accelerate delivery.'],['Product alignment','Brought Product and Engineering together, helping secure major enterprise deals.']],link:'/#impact',linkText:'Read the results'},
  source:{eyebrow:'The bookshelf',title:'Open source',subtitle:'Small tools, experiments, and references',body:'A few projects I share on GitHub. Each book opens its repository.',repositories:[['nutrizer','Nutrition tracking','nutrizer'],['mina-finansial','Personal finance','mina-finansial'],['CI3 AgGrid Server-Side','PHP data tables','codeigniter_aggrid'],['Game Center','Flutter architecture reference','game_center']]},
  reports:{eyebrow:'Inside the studio',title:'SCM Tools',subtitle:'PT. Tanjung Enim Lestari · 2019–2020',body:'Alongside ERP maintenance, I built tools to analyse and manage supply-chain information and deliver automated reports through a Telegram bot.',facts:[['Tools','PHP · MySQL · Oracle · Node.js']],image:'/assets/project-reports.webp',link:'/#work',linkText:'Other projects'}
};
